### ISSUE TITLE
Avoid defaulting to /bin/sh when adding a new user

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-admin#259]
When no selection under "avanced" is made the default shell for new users will be `/bin/sh` as it's always on top of the list and the selection is empty.
This can be annoying in the new user sessions, as most people are used to see the bash prompt in terminal windows.

![schermata-02-13-08-56-01](https://user-images.githubusercontent.com/10681413/153744433-1348ea0e-7e6f-4a76-96c5-5742fa1a1732.png)

##### Possible Solution

Make sure that if no selection is made shell defaults to /bin/bash if available.
##### Context

https://github.com/lxqt/lxqt/discussions/2163
##### System Information

* Distribution & Version: all

**Comment by tsujan** [comment]
The code gets the list from `/etc/shells` and in the order that's set in that file. I agree that most people may use bash but it feels a little strange to give it priority in the code.

BTW, since I have a habit of not using GUI for sensitive things like admin jobs, I can't call myself a user of `lxqt-admin` (installed it only recently). But I noticed that it lacked filtering.
